name: build
on:
  push:
    branches:
      - master
      - master_dev
  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: scripts/build.sh
        env:
          AWS_ACCESS_KEY_ID: \${{ secrets.DDE_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: \${{ secrets.DDE_AWS_SECRET_ACCESS_KEY }}
