name: build
on:
  push:
    branches:
      - master
      - master_dev
  pull_request:

jobs:
  build:
    runs-on: self-hosted-ubuntu-2004
    env:
      AWS_ACCESS_KEY_ID: \${{ secrets.DDE_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: \${{ secrets.DDE_AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to ECR
        run: aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 778379310836.dkr.ecr.eu-west-1.amazonaws.com

      - name: Build docker image
        run: ./scripts/docker-build.sh
